### ISSUE TITLE
CI failure for release builds

### ISSUE THREAD

**Issue by hossain-khan** [hossain-khan/android-keep-alive#83]
https://github.com/hossain-khan/android-keep-alive/actions/runs/15125334037/job/42516639398

The failure in the job is due to the task `:app:validateSigningRelease` failing during the build process. This task is related to the signing configuration in your Android Gradle project. Here's how you can resolve the issue:

### Cause
The error indicates that the signing configuration for the `release` build is either incomplete or invalid. This can happen due to missing or incorrect keystore information, such as:
- Missing `keystore` file.
- Missing or incorrect `keyAlias`, `keyPassword`, or `storePassword`.

### Solution
1. **Verify Your Signing Configuration:**
   Open your `build.gradle` file in the `app` module and check the `signingConfigs` block. Ensure all fields are properly filled.

   Example:
   ```gradle
   android {
       signingConfigs {
           release {
               storeFile file("path/to/keystore.jks")
               storePassword "your-store-password"
               keyAlias "your-key-alias"
               keyPassword "your-key-password"
           }
       }
       buildTypes {
           release {
               signingConfig signingConfigs.release
           }
       }
   }
   ```

   Replace the placeholder values (`path/to/keystore.jks`, `your-store-password`, `your-key-alias`, and `your-key-password`) with the actual values.

2. **Ensure the Keystore File is Present:**
   Verify that the `keystore.jks` file exists at the specified path in your project. If it is missing, add it to the specified location.

3. **Set Up Environment Variables for Sensitive Data:**
   If you do not want to hard-code sensitive information in your `build.gradle` file, use environment variables. Update your `build.gradle` file as follows:
   ```gradle
   android {
       signingConfigs {
           release {
               storeFile file(System.getenv("KEYSTORE_FILE"))
               storePassword System.getenv("KEYSTORE_PASSWORD")
               keyAlias System.getenv("KEY_ALIAS")
               keyPassword System.getenv("KEY_PASSWORD")
           }
       }
   }
   ```

   Then, set the environment variables in your CI/CD pipeline (e.g., GitHub Actions).

4. **Update GitHub Actions Workflow:**
   If you are using environment variables, ensure your GitHub Actions workflow file passes these variables to the build step. For example:
   ```yaml
   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Set up JDK
           uses: actions/setup-java@v3
           with:
             java-version: '17'

         - name: Build with Gradle
           env:
             KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
             KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
             KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
             KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
           run: ./gradlew assembleRelease
   ```

### Next Steps
- Verify and fix the signing configuration in your `build.gradle` file.
- Ensure the `keystore` file is available and correctly referenced.
- If needed, update your CI/CD workflow to handle sensitive information using environment variables or GitHub Secrets.

If you need further assistance, feel free to ask!
